In [2]:
import pandas as pd
import numpy as np

In [7]:
worksheet = pd.read_excel('worksheet_macro.xlsm', 'forpy', index_col=[0,1,2], head=[0,1,2])

In [9]:
worksheet.head()

                                           P1                   P2  \
Ticker Value    Type
AMZN   Date     Date      2013-03-31 00:00:00  2013-06-30 00:00:00
       Revenues Estimate              16144.5              15732.7
                Actual                  16070                15704
       EBIT     Estimate               95.286               62.404
                Actual                    181                   79

                                           P3                   P4  \
Ticker Value    Type
AMZN   Date     Date      2013-09-30 00:00:00  2013-12-31 00:00:00
       Revenues Estimate              16764.9              26063.1
                Actual                  17092                25587
       EBIT     Estimate              -17.595              467.552
                Actual                    -25                  510

                                           P5                   P6  \
Ticker Value    Type
AMZN   Date     Date      2014-03-31 00:00:00  2014-06-30 00:00:00
       Revenues Estimate              19431.2                19342
                Actual                  19741                19340
       EBIT     Estimate              204.608              -61.899
                Actual                    146                  -15

                                           P7                   P8  \
Ticker Value    Type
AMZN   Date     Date      2014-09-30 00:00:00  2014-12-31 00:00:00
       Revenues Estimate              20840.8              29672.4
                Actual                  20579                29328
       EBIT     Estimate             -428.106              178.599
                Actual                   -544                  591

                                           P9                  P10  \
Ticker Value    Type
AMZN   Date     Date      2015-03-31 00:00:00  2015-06-30 00:00:00
       Revenues Estimate              22391.4              22391.6
                Actual                  22717                23185
       EBIT     Estimate               29.671               35.944
                Actual                    255                  464

                                          P11                  P12  \
Ticker Value    Type
AMZN   Date     Date      2015-09-30 00:00:00  2015-12-31 00:00:00
       Revenues Estimate              24908.2              35934.3
                Actual                  25358                35747
       EBIT     Estimate               19.271              1241.02
                Actual                    406                 1108

                                          P13                  P14  \
Ticker Value    Type
AMZN   Date     Date      2016-03-31 00:00:00  2016-06-30 00:00:00
       Revenues Estimate              27978.8              29545.8
                Actual                  29128                30404
       EBIT     Estimate              563.571              913.745
                Actual                   1071                 1285

                                          P15                  P16  \
Ticker Value    Type
AMZN   Date     Date      2016-09-30 00:00:00  2016-12-31 00:00:00
       Revenues Estimate              32687.3              44676.8
                Actual                  32714                43741
       EBIT     Estimate              674.007              1118.29
                Actual                    575                 1255

                                          P17                  P18  \
Ticker Value    Type
AMZN   Date     Date      2017-03-31 00:00:00  2017-06-30 00:00:00
       Revenues Estimate              35299.2              37180.8
                Actual                  35714                37955
       EBIT     Estimate              896.328              1073.49
                Actual                   1005                  628

                                          P19                  P20
Ticker Value    Type
AMZN   Date     Date      2017-09-30 00:00:00  2017-12-31 00:00:00
       Revenues Estimate              42143.4              59829.6
                Actual                  43744                60453
       EBIT     Estimate              168.102              1499.05
                Actual                    347                 2127

In [8]:
worksheet.index

MultiIndex(levels=[['AAPL ', 'ABBV ', 'ADBE ', 'AMGN ', 'AMZN', 'AVGO ', 'BA ', 'BAC ', 'BKNG ', 'C ', 'CMCSA ', 'CSCO ', 'CVX ', 'DIS ', 'FB ', 'GE ', 'GOOG ', 'GOOGL ', 'HD ', 'HON ', 'IBM ', 'INTC ', 'JNJ ', 'JPM ', 'KO ', 'MA ', 'MCD ', 'MDT ', 'MMM ', 'MO ', 'MRK ', 'MSFT ', 'NFLX ', 'NVDA ', 'ORCL ', 'PEP ', 'PFE ', 'PG ', 'PM ', 'SLB ', 'T ', 'UNH ', 'UNP ', 'UTX ', 'V ', 'VZ ', 'WFC ', 'WMT ', 'XOM '], ['BV per share', 'Date', 'EBIT', 'EPS', 'FCF per share', 'Gross Margin', 'Revenues'], ['Actual', 'Date', 'Estimate']],
           labels=[[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45], [1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1, 6, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 1], [1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1]],
           names=['Ticker', 'Value', 'Type'])

In [11]:
worksheet.loc['AMZN']

                                         P1                   P2  \
Value         Type
Date          Date      2013-03-31 00:00:00  2013-06-30 00:00:00
Revenues      Estimate              16144.5              15732.7
              Actual                  16070                15704
EBIT          Estimate               95.286               62.404
              Actual                    181                   79
EPS           Estimate                0.078                0.054
              Actual                   0.18                -0.02
FCF per share Estimate                -4.33                1.463
              Actual               -6.68571            0.0525164
Gross Margin  Estimate               25.307                27.35
              Actual                 26.565              28.6233
BV per share  Estimate               16.694               17.972
              Actual                  18.53                19.11

                                         P3                   P4  \
Value         Type
Date          Date      2013-09-30 00:00:00  2013-12-31 00:00:00
Revenues      Estimate              16764.9              26063.1
              Actual                  17092                25587
EBIT          Estimate              -17.595              467.552
              Actual                    -25                  510
EPS           Estimate               -0.088                0.662
              Actual                  -0.09                 0.51
FCF per share Estimate                 2.16                9.385
              Actual               0.764192              10.2353
Gross Margin  Estimate               27.538               25.836
              Actual                27.6504              26.5017
BV per share  Estimate                 19.1               20.965
              Actual                  19.84                21.23

                                         P5                   P6  \
Value         Type
Date          Date      2014-03-31 00:00:00  2014-06-30 00:00:00
Revenues      Estimate              19431.2                19342
              Actual                  19741                19340
EBIT          Estimate              204.608              -61.899
              Actual                    146                  -15
EPS           Estimate                0.228               -0.146
              Actual                   0.23                -0.27
FCF per share Estimate               -1.657                1.008
              Actual               -7.78696            -0.926407
Gross Margin  Estimate               27.988               29.617
              Actual                 28.803              30.7187
BV per share  Estimate               22.871               24.178
              Actual                22.4522               22.948

                                         P7                   P8  \
Value         Type
Date          Date      2014-09-30 00:00:00  2014-12-31 00:00:00
Revenues      Estimate              20840.8              29672.4
              Actual                  20579                29328
EBIT          Estimate             -428.106              178.599
              Actual                   -544                  591
EPS           Estimate               -0.735                0.168
              Actual                  -0.95                 0.45
FCF per share Estimate                0.461                8.744
              Actual               0.840173              11.9785
Gross Margin  Estimate                29.27               28.167
              Actual                28.9227              29.5179
BV per share  Estimate               24.186               25.027
              Actual                 22.324              23.0989

                                         P9                  P10  \
Value         Type
Date          Date      2015-03-31 00:00:00  2015-06-30 00:00:00
Revenues      Estimate              22391.4              22391.6
              Actual                  22717                23185
EBIT          Estimate               29.671               35.944
              Actual                    255                  464
EPS           Estimate               -0.126               -0.138
              Actual                  -0.12                 0.19
FCF per share Estimate               -4.859                -0.14
              Actual               -5.08584              1.67521
Gross Margin  Estimate               30.692               32.885
              Actual                32.2314              34.6129
BV per share  Estimate               22.979               22.296
              Actual                23.3326              25.1453

                                        P11                  P12  \
Value         Type
Date          Date      2015-09-30 00:00:00  2015-12-31 00:00:00
Revenues      Estimate              24908.2              35934.3
              Actual                  25358                35747
EBIT          Estimate               19.271              1241.02
              Actual                    406                 1108
EPS           Estimate                -0.13                1.564
              Actual                   0.17                    1
FCF per share Estimate                1.406                9.456
              Actual                3.01493              14.4883
Gross Margin  Estimate               32.917               32.781
              Actual                33.9262              31.9076
BV per share  Estimate                22.88               26.062
              Actual                26.5032              28.4161

                                        P13                  P14  \
Value         Type
Date          Date      2016-03-31 00:00:00  2016-06-30 00:00:00
Revenues      Estimate              27978.8              29545.8
              Actual                  29128                30404
EBIT          Estimate              563.571              913.745
              Actual                   1071                 1285
EPS           Estimate                0.582                1.108
              Actual                   1.07                 1.78
FCF per share Estimate                0.296                3.979
              Actual               -6.63559              3.93882
Gross Margin  Estimate               33.521                36.08
              Actual                35.2307              36.9162
BV per share  Estimate               27.743               32.932
              Actual                 31.263                34.89

                                        P15                  P16  \
Value         Type
Date          Date      2016-09-30 00:00:00  2016-12-31 00:00:00
Revenues      Estimate              32687.3              44676.8
              Actual                  32714                43741
EBIT          Estimate              674.007              1118.29
              Actual                    575                 1255
EPS           Estimate                 0.78                1.347
              Actual                   0.52                 1.54
FCF per share Estimate                4.408               12.521
              Actual                4.89474              17.6268
Gross Margin  Estimate                35.16               32.957
              Actual                35.0125              33.7944
BV per share  Estimate               37.278               37.001
              Actual                 37.436                40.43

                                        P17                  P18  \
Value         Type
Date          Date      2017-03-31 00:00:00  2017-06-30 00:00:00
Revenues      Estimate              35299.2              37180.8
              Actual                  35714                37955
EBIT          Estimate              896.328              1073.49
              Actual                   1005                  628
EPS           Estimate                1.118                1.419
              Actual                   1.48                  0.4
FCF per share Estimate               -2.853                0.139
              Actual               -7.88075              1.53333
Gross Margin  Estimate               36.044               38.118
              Actual                37.1675              38.2137
BV per share  Estimate               43.063                 47.1
              Actual                 45.343               48.667

                                        P19                  P20
Value         Type
Date          Date      2017-09-30 00:00:00  2017-12-31 00:00:00
Revenues      Estimate              42143.4              59829.6
              Actual                  43744                60453
EBIT          Estimate              168.102              1499.05
              Actual                    347                 2127
EPS           Estimate                 0.03                1.848
              Actual                   0.52                 2.16
FCF per share Estimate                1.883               17.944
              Actual                4.35477               15.312
Gross Margin  Estimate               36.294               35.139
              Actual                37.0222              36.3224
BV per share  Estimate                57.58               49.107
              Actual                 51.158                57.25

In [16]:
worksheet.xs("Date", level="Type")

                               P1                   P2                   P3  \
Ticker Value
AMZN   Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
HD     Date   2012-04-30 00:00:00  2012-07-31 00:00:00  2012-10-31 00:00:00
DIS    Date   2012-12-31 00:00:00  2013-03-31 00:00:00  2013-06-30 00:00:00
CMCSA  Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
NFLX   Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
MCD    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
BKNG   Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
PG     Date   2012-09-30 00:00:00  2012-12-31 00:00:00  2013-03-31 00:00:00
KO     Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
PEP    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
PM     Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
WMT    Date   2012-04-30 00:00:00  2012-07-31 00:00:00  2012-10-31 00:00:00
MO     Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
XOM    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
CVX    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
SLB    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
JPM    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
BAC    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
WFC    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
C      Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
JNJ    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
UNH    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
PFE    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
MRK    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
ABBV   Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
AMGN   Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
MDT    Date   2012-07-31 00:00:00  2012-10-31 00:00:00  2013-01-31 00:00:00
BA     Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
MMM    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
HON    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
UNP    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
GE     Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
UTX    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
AAPL   Date   2012-12-31 00:00:00  2013-03-31 00:00:00  2013-06-30 00:00:00
MSFT   Date   2012-09-30 00:00:00  2012-12-31 00:00:00  2013-03-31 00:00:00
FB     Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
GOOG   Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
GOOGL  Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
V      Date   2012-12-31 00:00:00  2013-03-31 00:00:00  2013-06-30 00:00:00
INTC   Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
CSCO   Date   2012-10-31 00:00:00  2013-01-31 00:00:00  2013-04-30 00:00:00
MA     Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
NVDA   Date   2012-04-30 00:00:00  2012-07-31 00:00:00  2012-10-31 00:00:00
ORCL   Date   2012-08-31 00:00:00  2012-11-30 00:00:00  2013-02-28 00:00:00
ADBE   Date   2013-02-28 00:00:00  2013-05-31 00:00:00  2013-08-31 00:00:00
IBM    Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
AVGO   Date   2013-01-31 00:00:00  2013-04-30 00:00:00  2013-07-31 00:00:00
T      Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
VZ     Date   2013-03-31 00:00:00  2013-06-30 00:00:00  2013-09-30 00:00:00
       Date                   NaN                  NaN                  NaN

                               P4                   P5                   P6  \
Ticker Value
AMZN   Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
HD     Date   2013-01-31 00:00:00  2013-04-30 00:00:00  2013-07-31 00:00:00
DIS    Date   2013-09-30 00:00:00  2013-12-31 00:00:00  2014-03-31 00:00:00
CMCSA  Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
NFLX   Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
MCD    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
BKNG   Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
PG     Date   2013-06-30 00:00:00  2013-09-30 00:00:00  2013-12-31 00:00:00
KO     Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
PEP    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
PM     Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
WMT    Date   2013-01-31 00:00:00  2013-04-30 00:00:00  2013-07-31 00:00:00
MO     Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
XOM    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
CVX    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
SLB    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
JPM    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
BAC    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
WFC    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
C      Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
JNJ    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
UNH    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
PFE    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
MRK    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
ABBV   Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
AMGN   Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
MDT    Date   2013-04-30 00:00:00  2013-07-31 00:00:00  2013-10-31 00:00:00
BA     Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
MMM    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
HON    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
UNP    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
GE     Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
UTX    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
AAPL   Date   2013-09-30 00:00:00  2013-12-31 00:00:00  2014-03-31 00:00:00
MSFT   Date   2013-06-30 00:00:00  2013-09-30 00:00:00  2013-12-31 00:00:00
FB     Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
GOOG   Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
GOOGL  Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
V      Date   2013-09-30 00:00:00  2013-12-31 00:00:00  2014-03-31 00:00:00
INTC   Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
CSCO   Date   2013-07-31 00:00:00  2013-10-31 00:00:00  2014-01-31 00:00:00
MA     Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
NVDA   Date   2013-01-31 00:00:00  2013-04-30 00:00:00  2013-07-31 00:00:00
ORCL   Date   2013-05-31 00:00:00  2013-08-31 00:00:00  2013-11-30 00:00:00
ADBE   Date   2013-11-30 00:00:00  2014-02-28 00:00:00  2014-05-31 00:00:00
IBM    Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
AVGO   Date   2013-10-31 00:00:00  2014-01-31 00:00:00  2014-04-30 00:00:00
T      Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
VZ     Date   2013-12-31 00:00:00  2014-03-31 00:00:00  2014-06-30 00:00:00
       Date                   NaN                  NaN                  NaN

                               P7                   P8                   P9  \
Ticker Value
AMZN   Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
HD     Date   2013-10-31 00:00:00  2014-01-31 00:00:00  2014-04-30 00:00:00
DIS    Date   2014-06-30 00:00:00  2014-09-30 00:00:00  2014-12-31 00:00:00
CMCSA  Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
NFLX   Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
MCD    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
BKNG   Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
PG     Date   2014-03-31 00:00:00  2014-06-30 00:00:00  2014-09-30 00:00:00
KO     Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
PEP    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
PM     Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
WMT    Date   2013-10-31 00:00:00  2014-01-31 00:00:00  2014-04-30 00:00:00
MO     Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
XOM    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
CVX    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
SLB    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
JPM    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
BAC    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
WFC    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
C      Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
JNJ    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
UNH    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
PFE    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
MRK    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
ABBV   Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
AMGN   Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
MDT    Date   2014-01-31 00:00:00  2014-04-30 00:00:00  2014-07-31 00:00:00
BA     Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
MMM    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
HON    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
UNP    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
GE     Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
UTX    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
AAPL   Date   2014-06-30 00:00:00  2014-09-30 00:00:00  2014-12-31 00:00:00
MSFT   Date   2014-03-31 00:00:00  2014-06-30 00:00:00  2014-09-30 00:00:00
FB     Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
GOOG   Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
GOOGL  Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
V      Date   2014-06-30 00:00:00  2014-09-30 00:00:00  2014-12-31 00:00:00
INTC   Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
CSCO   Date   2014-04-30 00:00:00  2014-07-31 00:00:00  2014-10-31 00:00:00
MA     Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
NVDA   Date   2013-10-31 00:00:00  2014-01-31 00:00:00  2014-04-30 00:00:00
ORCL   Date   2014-02-28 00:00:00  2014-05-31 00:00:00  2014-08-31 00:00:00
ADBE   Date   2014-08-31 00:00:00  2014-11-30 00:00:00  2015-02-28 00:00:00
IBM    Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
AVGO   Date   2014-07-31 00:00:00  2014-10-31 00:00:00  2015-01-31 00:00:00
T      Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
VZ     Date   2014-09-30 00:00:00  2014-12-31 00:00:00  2015-03-31 00:00:00
       Date                   NaN                  NaN                  NaN

                              P10                  P11                  P12  \
Ticker Value
AMZN   Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
HD     Date   2014-07-31 00:00:00  2014-10-31 00:00:00  2015-01-31 00:00:00
DIS    Date   2015-03-31 00:00:00  2015-06-30 00:00:00  2015-09-30 00:00:00
CMCSA  Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
NFLX   Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
MCD    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
BKNG   Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
PG     Date   2014-12-31 00:00:00  2015-03-31 00:00:00  2015-06-30 00:00:00
KO     Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
PEP    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
PM     Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
WMT    Date   2014-07-31 00:00:00  2014-10-31 00:00:00  2015-01-31 00:00:00
MO     Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
XOM    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
CVX    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
SLB    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
JPM    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
BAC    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
WFC    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
C      Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
JNJ    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
UNH    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
PFE    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
MRK    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
ABBV   Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
AMGN   Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
MDT    Date   2014-10-31 00:00:00  2015-01-31 00:00:00  2015-04-30 00:00:00
BA     Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
MMM    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
HON    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
UNP    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
GE     Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
UTX    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
AAPL   Date   2015-03-31 00:00:00  2015-06-30 00:00:00  2015-09-30 00:00:00
MSFT   Date   2014-12-31 00:00:00  2015-03-31 00:00:00  2015-06-30 00:00:00
FB     Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
GOOG   Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
GOOGL  Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
V      Date   2015-03-31 00:00:00  2015-06-30 00:00:00  2015-09-30 00:00:00
INTC   Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
CSCO   Date   2015-01-31 00:00:00  2015-04-30 00:00:00  2015-07-31 00:00:00
MA     Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
NVDA   Date   2014-07-31 00:00:00  2014-10-31 00:00:00  2015-01-31 00:00:00
ORCL   Date   2014-11-30 00:00:00  2015-02-28 00:00:00  2015-05-31 00:00:00
ADBE   Date   2015-05-31 00:00:00  2015-08-31 00:00:00  2015-11-30 00:00:00
IBM    Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
AVGO   Date   2015-04-30 00:00:00  2015-07-31 00:00:00  2015-10-31 00:00:00
T      Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
VZ     Date   2015-06-30 00:00:00  2015-09-30 00:00:00  2015-12-31 00:00:00
       Date                   NaN                  NaN                  NaN

                              P13                  P14                  P15  \
Ticker Value
AMZN   Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
HD     Date   2015-04-30 00:00:00  2015-07-31 00:00:00  2015-10-31 00:00:00
DIS    Date   2015-12-31 00:00:00  2016-03-31 00:00:00  2016-06-30 00:00:00
CMCSA  Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
NFLX   Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
MCD    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
BKNG   Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
PG     Date   2015-09-30 00:00:00  2015-12-31 00:00:00  2016-03-31 00:00:00
KO     Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
PEP    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
PM     Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
WMT    Date   2015-04-30 00:00:00  2015-07-31 00:00:00  2015-10-31 00:00:00
MO     Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
XOM    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
CVX    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
SLB    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
JPM    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
BAC    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
WFC    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
C      Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
JNJ    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
UNH    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
PFE    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
MRK    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
ABBV   Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
AMGN   Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
MDT    Date   2015-07-31 00:00:00  2015-10-31 00:00:00  2016-01-31 00:00:00
BA     Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
MMM    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
HON    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
UNP    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
GE     Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
UTX    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
AAPL   Date   2015-12-31 00:00:00  2016-03-31 00:00:00  2016-06-30 00:00:00
MSFT   Date   2015-09-30 00:00:00  2015-12-31 00:00:00  2016-03-31 00:00:00
FB     Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
GOOG   Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
GOOGL  Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
V      Date   2015-12-31 00:00:00  2016-03-31 00:00:00  2016-06-30 00:00:00
INTC   Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
CSCO   Date   2015-10-31 00:00:00  2016-01-31 00:00:00  2016-04-30 00:00:00
MA     Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
NVDA   Date   2015-04-30 00:00:00  2015-07-31 00:00:00  2015-10-31 00:00:00
ORCL   Date   2015-08-31 00:00:00  2015-11-30 00:00:00  2016-02-28 00:00:00
ADBE   Date   2016-02-28 00:00:00  2016-05-31 00:00:00  2016-08-31 00:00:00
IBM    Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
AVGO   Date   2016-01-31 00:00:00  2016-04-30 00:00:00  2016-07-31 00:00:00
T      Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
VZ     Date   2016-03-31 00:00:00  2016-06-30 00:00:00  2016-09-30 00:00:00
       Date                   NaN                  NaN                  NaN

                              P16                  P17                  P18  \
Ticker Value
AMZN   Date   2016-12-31 00:00:00  2017-03-31 00:00:00  2017-06-30 00:00:00
HD     Date   2016-01-31 00:00:00  2016-04-30 00:00:00  2016-07-31 00:00:00
DIS    Date   2016-09-30 00:00:00  2016-12-31 00:00:00  2017-03-31 00:00:00
CMCSA  Date   2016-12-31 00:00:00  2017-03-31 00:00:00  2017-06-30 00:00:00
NFLX   Date   2016-12-31 00:00:00  2017-03-31 00:00:00  2017-06-30 00:00:00

In [21]:
idx = pd.IndexSlice

In [61]:
worksheet.loc[idx["AMZN",:,'Date'],:].values.item(0)

datetime.datetime(2013, 3, 31, 0, 0)

In [38]:
worksheet.index.levels[0]

Index(['AAPL ', 'ABBV ', 'ADBE ', 'AMGN ', 'AMZN', 'AVGO ', 'BA ', 'BAC ',
       'BKNG ', 'C ', 'CMCSA ', 'CSCO ', 'CVX ', 'DIS ', 'FB ', 'GE ', 'GOOG ',
       'GOOGL ', 'HD ', 'HON ', 'IBM ', 'INTC ', 'JNJ ', 'JPM ', 'KO ', 'MA ',
       'MCD ', 'MDT ', 'MMM ', 'MO ', 'MRK ', 'MSFT ', 'NFLX ', 'NVDA ',
       'ORCL ', 'PEP ', 'PFE ', 'PG ', 'PM ', 'SLB ', 'T ', 'UNH ', 'UNP ',
       'UTX ', 'V ', 'VZ ', 'WFC ', 'WMT ', 'XOM '],
      dtype='object', name='Ticker')